# Generated by Django 6.0.1 on 2026-02-02 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Автоматически генерируется из названия",
                        max_length=200,
                        unique=True,
                        verbose_name="URL slug",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/%Y/%m/%d/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="meta заголовок"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="meta описание"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="порядок сортировки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлена"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="название")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Автоматически генерируется из названия",
                        max_length=200,
                        unique=True,
                        verbose_name="URL slug",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена в валюте",
                        max_digits=10,
                        verbose_name="цена",
                    ),
                ),
                (
                    "compare_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Старая цена (для отображения скидки)",
                        max_digits=10,
                        null=True,
                        verbose_name="цена для сравнения",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Цена закупки (не показывается покупателям)",
                        max_digits=10,
                        null=True,
                        verbose_name="себестоимость",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="количество на складе"
                    ),
                ),
                (
                    "track_inventory",
                    models.BooleanField(
                        default=True,
                        help_text="Если выключено, товар всегда доступен",
                        verbose_name="отслеживать запасы",
                    ),
                ),
                (
                    "allow_backorder",
                    models.BooleanField(
                        default=False,
                        help_text="Можно ли заказать при нулевом остатке",
                        verbose_name="разрешить предзаказ",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/%Y/%m/%d/",
                        verbose_name="главное изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Отображается на главной странице",
                        verbose_name="рекомендуемый",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="meta заголовок"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="meta описание"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="вес (кг)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлён"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/%Y/%m/%d/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Описание изображения для SEO",
                        max_length=200,
                        verbose_name="альтернативный текст",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="products_ca_slug_da4386_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active"], name="products_ca_is_acti_a2d000_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="products_pr_is_acti_2fee29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="products_pr_categor_50f5f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="products_pr_created_bce1a7_idx"
            ),
        ),
    ]
