# Generated by Django 6.0.1 on 2026-02-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "fix_cart_item_prices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price_at_addition",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="цена при добавлении",
            ),
        ),
    ]
