# Generated by Django 6.0.1 on 2026-02-03 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(
                        help_text="Уникальный ID события от Stripe",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe Event ID",
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Checkout Session ID"
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Payment Intent ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("checkout.session.created", "Сессия создана"),
                            ("checkout.session.completed", "Оплата завершена"),
                            ("payment_intent.succeeded", "Платёж успешен"),
                            ("payment_intent.payment_failed", "Платёж провален"),
                            ("charge.succeeded", "Списание успешно"),
                            ("charge.failed", "Списание провалено"),
                            ("other", "Другое событие"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="тип события",
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        default=dict,
                        help_text="Полные данные события от Stripe",
                        verbose_name="данные события",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="обработано"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="обработано"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="сообщение об ошибке"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_payments",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe платёж",
                "verbose_name_plural": "Stripe платежи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stripe_event_id"],
                        name="payments_st_stripe__cca23f_idx",
                    ),
                    models.Index(
                        fields=["stripe_checkout_session_id"],
                        name="payments_st_stripe__d34ff5_idx",
                    ),
                    models.Index(
                        fields=["order"], name="payments_st_order_i_63d7ec_idx"
                    ),
                    models.Index(
                        fields=["processed"], name="payments_st_process_84cd16_idx"
                    ),
                ],
            },
        ),
    ]
