# Generated by Django 6.0.1 on 2026-02-04 17:56

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.CustomUserManager()),
            ],
        ),
    ]
